### ISSUE TITLE
eosio 1.8.x compatibility?

### ISSUE THREAD

**Issue by pkuphy** [cc32d9/eos_zmq_plugin#10]
Hi, the current code base is not compatible with eosio 1.8.x. Any plan for updating?

**Comment by igorls** [comment]
Hey, thanks for reporting, we are working on it based on v1.8.1. A patch should be ready soon

**Comment by pkuphy** [comment]
Well, I use this fork https://github.com/joaoocb/eos_zmq_plugin for newer nodeos.
