### ISSUE TITLE
build fail on centos7

### ISSUE THREAD

**Issue by farss** [cc32d9/eos_zmq_plugin#3]
/root/build/eos_zmq_plugin/zmq_plugin.cpp: At global scope:
/root/build/eos_zmq_plugin/zmq_plugin.cpp:113:14: error: declaration of ‘eosio::chain::symbol zmqplugin::token::open::symbol’ [-fpermissive]
       symbol symbol;
              ^~~~~~
In file included from /opt/eos/libraries/chain/include/eosio/chain/asset.hpp:8:0,
                 from /opt/eos/plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp:7,
                 from /root/build/eos_zmq_plugin/zmq_plugin.cpp:14:
/opt/eos/libraries/chain/include/eosio/chain/symbol.hpp:61:13: error: changes meaning of ‘symbol’ from ‘class eosio::chain::symbol’ [-fpermissive]
       class symbol {
             ^~~~~~

**Comment by pkuphy** [comment]
@farss How did you solve this problem?
